version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garmin_app
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=garmin_data
      - DB_USER=postgres
      - DB_PASSWORD=admin1
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: garmin_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: