# Generated by Django 4.2.7 on 2025-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'activity_id'], name='activities__user_id_27dc1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('activity_id__isnull', False)), fields=('user', 'activity_id'), name='unique_user_activity_id'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('user', 'activity_name', 'start_time'), name='unique_user_activity_name_time'),
        ),
    ]
