# Secrets pour l'application Streamlit Coach AI
# Configuration API FastAPI unifiée

API_KEY = "coach_ai_secure_key_2025"

# Configuration des URLs
FASTAPI_URL = "http://localhost:8000"
DJANGO_URL = "http://localhost:8002"