global:
  smtp_smarthost: 'localhost:1025'
  smtp_from: 'alertmanager@coachail.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/webhook'

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/webhook/critical'