# Docker Compose configuration for Supabase PostgreSQL

services:
  # Service Django (Web + API) avec Supabase PostgreSQL
  django:
    container_name: coach_ai_django_supabase
    build:
      context: ..
      dockerfile: deployment/django.Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
      - DB_TYPE=postgresql
      - DB_HOST=db.tbsxjflpsbiuklxzjwai.supabase.co
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=gN0qC8NHDzjOh1LH
    volumes:
      - ../data:/app/data
      - ../E3_model_IA/backend/django_app/logs:/app/logs
      - ../E3_model_IA/backend/django_app/templates:/app/templates
      - ../E3_model_IA/backend/django_app/static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service FastAPI (IA) avec Supabase
  fastapi:
    container_name: coach_ai_fastapi_supabase
    build:
      context: ..
      dockerfile: deployment/fastapi.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
      - DB_TYPE=postgresql
      - DATABASE_URL=postgresql://postgres:gN0qC8NHDzjOh1LH@db.tbsxjflpsbiuklxzjwai.supabase.co:5432/postgres
      - API_KEY=coach_ai_secure_key_2025
    volumes:
      - ../data:/app/data
      - ../knowledge_base:/app/knowledge_base
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - django

  # Service Streamlit (Interface utilisateur)
  streamlit:
    container_name: coach_ai_streamlit_supabase
    build:
      context: ..
      dockerfile: deployment/streamlit.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
    volumes:
      - ../data:/app/data
      - ../knowledge_base:/app/knowledge_base
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - fastapi


  # Nginx reverse proxy (optionnel)
  nginx:
    image: nginx:alpine
    container_name: coach_ai_nginx_supabase
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-supabase.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
      - django
      - streamlit
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: coach_ai_supabase_network

volumes:
  coach_ai_data:
    driver: local
  coach_ai_logs:
    driver: local