global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (métriques système)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # === ARCHITECTURE COACH AI ===
  
  # FastAPI - API Unifiée (Données + IA)
  - job_name: 'coach-api-fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  # FastAPI - Métriques Agent IA (port séparé)
  - job_name: 'coach-ai-metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Django - Interface Admin + Génération Plans
  - job_name: 'coach-django'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Streamlit - Interface Utilisateur (port corrigé)
  - job_name: 'coach-streamlit'
    static_configs:
      - targets: ['host.docker.internal:8502']
    metrics_path: '/_stcore/metrics'
    scrape_interval: 15s
    
  # PostgreSQL - Base de données centrale
  - job_name: 'coach-postgresql'
    static_configs:
      - targets: ['host.docker.internal:5432']
    scrape_interval: 30s
    
  # === SERVICES SYSTÈME ===
  
  # Métriques Docker 
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s