apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "5s"
      
# Loki service not available in this deployment
#  - name: Loki
#    type: loki
#    access: proxy  
#    url: http://loki:3100
#    editable: true
#    jsonData:
#      httpMethod: POST
#      maxLines: 1000