name: CD Production

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create production .env file
        run: |
          cat <<EOF > .env
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          API_KEY=${{ secrets.API_KEY }}
          DEBUG=False
          ALLOWED_HOSTS=localhost,127.0.0.1
          EOF

      - name: Deploy to production
        run: |
          echo "🚀 Déploiement PRODUCTION en cours..."
          
          cd deployment
          
          # Arrêter et nettoyer
          docker compose -f docker-compose-production.yml down || true
          docker system prune -f
          
          # Déployer avec la config production
          docker compose -f docker-compose-production.yml up -d --build
          
          # Attendre le démarrage
          sleep 45
          
          # Vérifier les services
          docker compose -f docker-compose-production.yml ps

      - name: Production health check
        run: |
          echo "🏥 Health check PRODUCTION..."
          
          # Tests de santé avec timeout
          timeout 10 curl -f http://localhost:8002/admin/ || echo "⚠️ Django"
          timeout 10 curl -f http://localhost:8000/docs || echo "⚠️ FastAPI"
          timeout 10 curl -f http://localhost:8501/ || echo "⚠️ Streamlit"

      - name: Production status
        run: |
          echo "✅ PRODUCTION déployée sur main"
          echo "🌐 Services:"
          echo "   - Django: http://localhost:8002"
          echo "   - FastAPI: http://localhost:8000"
          echo "   - Streamlit: http://localhost:8501" 