name: CD Pipelines

on:
  push:
    branches: [ developp ]

permissions:
  contents: read

jobs:
  build-only:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Dockerfiles
        run: |
          echo "Validating Django Dockerfile exists..."
          test -f deployment/django.Dockerfile && echo "✅ Django Dockerfile found" || echo "❌ Django Dockerfile missing"
          echo "Validating FastAPI Dockerfile exists..." 
          test -f deployment/fastapi.Dockerfile && echo "✅ FastAPI Dockerfile found" || echo "❌ FastAPI Dockerfile missing"
          echo "Dockerfile validation completed"

      - name: No deployment target
        run: echo "No server configured for deployment yet."