name: CD Simple

on:
  push:
    branches: [ developp ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat <<EOF > .env
          DJANGO_SECRET_KEY=dev-secret-key-123
          POSTGRES_DB=coach_ai_db
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=dev-password
          DATABASE_URL=postgresql://postgres:dev-password@localhost:5432/coach_ai_db
          API_KEY=dev-api-key
          DEBUG=True
          EOF

      - name: Deploy
        run: |
          echo "🚀 Déploiement..."
          
          # Copier .env
          cp .env deployment/.env
          
          # Déployer
          cd deployment
          docker compose -f docker-compose-supabase.yml up -d --build
          
          echo "✅ Déploiement terminé !"
