name: CD Pipelines

on:
  push:
    branches: [ developp ]

permissions:
  contents: read

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug — check .env presence
        run: ls -la

      - name: Run docker compose (build only, no deploy)
        working-directory: .
        run: |
          echo "Running docker compose (build only, no deploy)..."
          docker compose -f deployment/docker-compose-supabase.yml up -d --build

      - name: No deployment target yet
        run: echo "No server configured for deployment yet."
